//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("forlabaModel", "FK_Answer_Question", "Question", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebAspNet2.Models.Question), "Answer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebAspNet2.Models.Answer), true)]

#endregion

namespace WebAspNet2.Models
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class forlabaEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект forlabaEntities, используя строку соединения из раздела "forlabaEntities" файла конфигурации приложения.
        /// </summary>
        public forlabaEntities() : base("name=forlabaEntities", "forlabaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта forlabaEntities.
        /// </summary>
        public forlabaEntities(string connectionString) : base(connectionString, "forlabaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта forlabaEntities.
        /// </summary>
        public forlabaEntities(EntityConnection connection) : base(connection, "forlabaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Answer> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answer>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answer> _Answers;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<Question> Questions
        {
            get
            {
                if ((_Questions == null))
                {
                    _Questions = base.CreateObjectSet<Question>("Questions");
                }
                return _Questions;
            }
        }
        private ObjectSet<Question> _Questions;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Answers. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToAnswers(Answer answer)
        {
            base.AddObject("Answers", answer);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet People. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet Questions. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToQuestions(Question question)
        {
            base.AddObject("Questions", question);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="forlabaModel", Name="Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answer : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Answer.
        /// </summary>
        /// <param name="questionNumber">Исходное значение свойства QuestionNumber.</param>
        /// <param name="personal">Исходное значение свойства Personal.</param>
        /// <param name="answerTime">Исходное значение свойства AnswerTime.</param>
        /// <param name="answerText">Исходное значение свойства AnswerText.</param>
        public static Answer CreateAnswer(global::System.Int32 questionNumber, global::System.Guid personal, global::System.DateTime answerTime, global::System.String answerText)
        {
            Answer answer = new Answer();
            answer.QuestionNumber = questionNumber;
            answer.Personal = personal;
            answer.AnswerTime = answerTime;
            answer.AnswerText = answerText;
            return answer;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QuestionNumber
        {
            get
            {
                return _QuestionNumber;
            }
            set
            {
                if (_QuestionNumber != value)
                {
                    OnQuestionNumberChanging(value);
                    ReportPropertyChanging("QuestionNumber");
                    _QuestionNumber = StructuralObject.SetValidValue(value, "QuestionNumber");
                    ReportPropertyChanged("QuestionNumber");
                    OnQuestionNumberChanged();
                }
            }
        }
        private global::System.Int32 _QuestionNumber;
        partial void OnQuestionNumberChanging(global::System.Int32 value);
        partial void OnQuestionNumberChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Personal
        {
            get
            {
                return _Personal;
            }
            set
            {
                if (_Personal != value)
                {
                    OnPersonalChanging(value);
                    ReportPropertyChanging("Personal");
                    _Personal = StructuralObject.SetValidValue(value, "Personal");
                    ReportPropertyChanged("Personal");
                    OnPersonalChanged();
                }
            }
        }
        private global::System.Guid _Personal;
        partial void OnPersonalChanging(global::System.Guid value);
        partial void OnPersonalChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AnswerTime
        {
            get
            {
                return _AnswerTime;
            }
            set
            {
                OnAnswerTimeChanging(value);
                ReportPropertyChanging("AnswerTime");
                _AnswerTime = StructuralObject.SetValidValue(value, "AnswerTime");
                ReportPropertyChanged("AnswerTime");
                OnAnswerTimeChanged();
            }
        }
        private global::System.DateTime _AnswerTime;
        partial void OnAnswerTimeChanging(global::System.DateTime value);
        partial void OnAnswerTimeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AnswerText
        {
            get
            {
                return _AnswerText;
            }
            set
            {
                OnAnswerTextChanging(value);
                ReportPropertyChanging("AnswerText");
                _AnswerText = StructuralObject.SetValidValue(value, false, "AnswerText");
                ReportPropertyChanged("AnswerText");
                OnAnswerTextChanged();
            }
        }
        private global::System.String _AnswerText;
        partial void OnAnswerTextChanging(global::System.String value);
        partial void OnAnswerTextChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("forlabaModel", "FK_Answer_Question", "Question")]
        public Question Question
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("forlabaModel.FK_Answer_Question", "Question").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("forlabaModel.FK_Answer_Question", "Question").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Question> QuestionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Question>("forlabaModel.FK_Answer_Question", "Question");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Question>("forlabaModel.FK_Answer_Question", "Question", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="forlabaModel", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Person.
        /// </summary>
        /// <param name="id">Исходное значение свойства id.</param>
        /// <param name="lastName">Исходное значение свойства lastName.</param>
        /// <param name="firstName">Исходное значение свойства firstName.</param>
        /// <param name="age">Исходное значение свойства Age.</param>
        /// <param name="hasJob">Исходное значение свойства HasJob.</param>
        public static Person CreatePerson(global::System.Guid id, global::System.String lastName, global::System.String firstName, global::System.Int32 age, global::System.Boolean hasJob)
        {
            Person person = new Person();
            person.id = id;
            person.lastName = lastName;
            person.firstName = firstName;
            person.Age = age;
            person.HasJob = hasJob;
            return person;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Guid _id;
        partial void OnidChanging(global::System.Guid value);
        partial void OnidChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false, "lastName");
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false, "firstName");
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Partonic
        {
            get
            {
                return _Partonic;
            }
            set
            {
                OnPartonicChanging(value);
                ReportPropertyChanging("Partonic");
                _Partonic = StructuralObject.SetValidValue(value, true, "Partonic");
                ReportPropertyChanged("Partonic");
                OnPartonicChanged();
            }
        }
        private global::System.String _Partonic;
        partial void OnPartonicChanging(global::System.String value);
        partial void OnPartonicChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, "Age");
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.Int32 _Age;
        partial void OnAgeChanging(global::System.Int32 value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true, "Gender");
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HasJob
        {
            get
            {
                return _HasJob;
            }
            set
            {
                OnHasJobChanging(value);
                ReportPropertyChanging("HasJob");
                _HasJob = StructuralObject.SetValidValue(value, "HasJob");
                ReportPropertyChanged("HasJob");
                OnHasJobChanged();
            }
        }
        private global::System.Boolean _HasJob;
        partial void OnHasJobChanging(global::System.Boolean value);
        partial void OnHasJobChanged();

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="forlabaModel", Name="Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Question : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта Question.
        /// </summary>
        /// <param name="number">Исходное значение свойства Number.</param>
        /// <param name="questionText">Исходное значение свойства QuestionText.</param>
        public static Question CreateQuestion(global::System.Int32 number, global::System.String questionText)
        {
            Question question = new Question();
            question.Number = number;
            question.QuestionText = questionText;
            return question;
        }

        #endregion

        #region Простые свойства
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                if (_Number != value)
                {
                    OnNumberChanging(value);
                    ReportPropertyChanging("Number");
                    _Number = StructuralObject.SetValidValue(value, "Number");
                    ReportPropertyChanged("Number");
                    OnNumberChanged();
                }
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionText
        {
            get
            {
                return _QuestionText;
            }
            set
            {
                OnQuestionTextChanging(value);
                ReportPropertyChanging("QuestionText");
                _QuestionText = StructuralObject.SetValidValue(value, false, "QuestionText");
                ReportPropertyChanged("QuestionText");
                OnQuestionTextChanged();
            }
        }
        private global::System.String _QuestionText;
        partial void OnQuestionTextChanging(global::System.String value);
        partial void OnQuestionTextChanged();

        #endregion

        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("forlabaModel", "FK_Answer_Question", "Answer")]
        public EntityCollection<Answer> Answers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Answer>("forlabaModel.FK_Answer_Question", "Answer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Answer>("forlabaModel.FK_Answer_Question", "Answer", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
